<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="diplomaticpulse.tests.test_fire_me.TestParsingdates-20220209183818" skipped="0" tests="1" time="0.000" timestamp="2022-02-09T18:38:18">
	<testcase classname="diplomaticpulse.tests.test_fire_me.TestParsingdates" name="test_fire_me" time="0.000" timestamp="2022-02-09T18:38:18">
		<error message="'str' object is not callable" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/home/alattab/projects/docker/DiplomaticPulse/diplomaticpulse/tests/test_fire_me.py", line 23, in test_fire_me
    result = dates_parser.fire_me(func_, date_string)
  File "/home/alattab/projects/docker/DiplomaticPulse/diplomaticpulse/parsers/dates_parser.py", line 48, in fire_me
    return func_name(date_string)
TypeError: 'str' object is not callable
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
